# Generated by Django 3.2 on 2021-04-13 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='positivo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
